### PR TITLE
feat(emailRegex): case insensitive

### PR DESCRIPTION
**Pull request by jasonmacgowan**
email validation regex shouldn't be case sensitive by default

### CODE REVIEW

**Comment by jasonmacgowan** [comment]
@Chocrates tests are failing against `master` as well, do you know what's up with that?

**Comment by Chocrates** [comment]
try `npm install --force https://github.com/Chocrates/octomock.git`  
The `addLabels` function may be new to the mocking library.  
Do you know of a better way to package it so npm can grab updates?

**Comment by jasonmacgowan** [comment]
@Chocrates that worked, I'm blowing up my `node_modules` `package-lock.json` and will add that commit

**Comment by Chocrates** [comment]
node_modules isn't in this repo, I don't know why the tests failed actually...
I need to read up on package-lock perhaps

**Comment by jasonmacgowan** [comment]
I think if my `node_modules` already has the reference to the octokit it won't update it, and I was afraid my package-lock.json would have an older version referenced.  all is good now.

**Pull request merged**
